#!/usr/bin/env python3
"""
Generates an index.html page that displays all diagram images.
Usage: python scripts/generate_index.py <images_dir> <output_file>
"""

import os
import sys

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} <images_dir> <output_file>", file=sys.stderr)
    sys.exit(1)

IMAGES_DIR = sys.argv[1]
OUTPUT_FILE = sys.argv[2]

if not os.path.isdir(IMAGES_DIR):
    print(f"Error: images directory '{IMAGES_DIR}' does not exist.", file=sys.stderr)
    sys.exit(1)

IMAGE_EXTENSIONS = {".png", ".svg", ".jpg", ".jpeg"}


def find_images(directory):
    images = []
    for fname in sorted(os.listdir(directory)):
        ext = os.path.splitext(fname)[1].lower()
        if ext in IMAGE_EXTENSIONS:
            images.append(fname)
    return images


def title_from_filename(fname):
    name = os.path.splitext(fname)[0]
    return name.replace("_", " ").replace("-", " ").title()


def generate_html(images):
    cards = ""
    if images:
        for img in images:
            title = title_from_filename(img)
            cards += f"""
        <div class="card">
          <h2>{title}</h2>
          <a href="{img}" target="_blank">
            <img src="{img}" alt="{title}" loading="lazy" />
          </a>
          <p class="caption"><a href="{img}" download>Download</a></p>
        </div>"""
    else:
        cards = '<p class="empty">No diagrams found yet.</p>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>zuzu-diagrams</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background: #f6f8fa;
      color: #24292f;
      padding: 2rem 1rem;
    }}
    header {{
      text-align: center;
      margin-bottom: 2.5rem;
    }}
    header h1 {{ font-size: 2rem; margin-bottom: 0.4rem; }}
    header p {{ color: #57606a; font-size: 1rem; }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(min(100%, 480px), 1fr));
      gap: 1.5rem;
      max-width: 1200px;
      margin: 0 auto;
    }}
    .card {{
      background: #fff;
      border: 1px solid #d0d7de;
      border-radius: 8px;
      padding: 1.25rem;
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
    }}
    .card h2 {{ font-size: 1.1rem; }}
    .card img {{
      width: 100%;
      height: auto;
      border: 1px solid #d0d7de;
      border-radius: 4px;
      background: #fff;
    }}
    .caption {{ font-size: 0.85rem; color: #57606a; text-align: right; }}
    .caption a {{ color: #0969da; text-decoration: none; }}
    .caption a:hover {{ text-decoration: underline; }}
    .empty {{ text-align: center; color: #57606a; margin-top: 3rem; font-size: 1.1rem; }}
    footer {{
      text-align: center;
      margin-top: 3rem;
      font-size: 0.8rem;
      color: #57606a;
    }}
    footer a {{ color: #0969da; text-decoration: none; }}
  </style>
</head>
<body>
  <header>
    <h1>zuzu-diagrams</h1>
    <p>Architecture diagrams generated with <a href="https://github.com/mingrammer/diagrams" target="_blank">mingrammer/diagrams</a></p>
  </header>
  <main class="grid">{cards}
  </main>
  <footer>
    <p>Auto-generated by GitHub Actions &mdash; <a href="https://github.com/teamzuzu/zuzu-diagrams" target="_blank">View source</a></p>
  </footer>
</body>
</html>
"""


def main():
    images = find_images(IMAGES_DIR)
    print(f"Found {len(images)} image(s): {images}")
    html = generate_html(images)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"Written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
